name: database_servers_local

on: [push]

jobs:
  test_mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test mysql
        run: |
          cd mysql
          ./start_system.sh
  test_postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test postgres
        run: |
          cd postgres
          ./start_system.sh